# Project-wide Gradle settings.
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx6144m -XX:+UseG1GC -XX:+ParallelRefProcEnabled -Dfile.encoding=UTF-8
# Temporarily disabling parallel and configuration-cache to resolve InterruptedException
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.vfs.watch=true
kotlin.incremental=true
kotlin.incremental.useClasspathSnapshot=true
kotlin.daemon.jvmargs=-Xmx2048m
org.gradle.configuration-cache.problems=warn

android.useAndroidX=true
android.enableJetifier=false
android.deploy.changeConfig=true