package com.example.dental_shade_app

import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.Canvas
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.net.Uri
import android.os.Environment
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.*

class PdfReportGenerator(private val context: Context) {

    fun generateReport(scanResult: ScanResult, patient: Patient?): File? {
        val pdfDocument = PdfDocument()
        val paint = Paint()
        val titlePaint = Paint()

        // Page description: A4 size is roughly 595 x 842 points
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create()
        val page = pdfDocument.startPage(pageInfo)
        val canvas: Canvas = page.canvas

        // Draw Logo / App Name
        titlePaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        titlePaint.textSize = 24f
        titlePaint.color = 0xFF6366F1.toInt() // PortalAccent
        canvas.drawText("ShadeScan AI", 40f, 50f, titlePaint)

        // Draw Horizontal Line
        paint.color = 0xFFE2E8F0.toInt() // PortalDivider
        canvas.drawRect(40f, 70f, 555f, 72f, paint)

        // Draw Scan Date
        paint.color = 0xFF64748B.toInt() // PortalTextMuted
        paint.textSize = 12f
        val sdf = SimpleDateFormat("EEEE, MMM dd, yyyy - hh:mm a", Locale.getDefault())
        val dateString = sdf.format(Date(scanResult.dateTime))
        canvas.drawText("Scan Date: $dateString", 40f, 95f, paint)

        // Draw Patient Info
        paint.color = 0xFF1E293B.toInt() // PortalTextMain
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        paint.textSize = 14f
        canvas.drawText("PATIENT DETAILS", 40f, 130f, paint)
        
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
        canvas.drawText("Name: ${patient?.name ?: "Quick Scan"}", 40f, 150f, paint)
        if (patient != null) {
            canvas.drawText("Age: ${patient.age} | Gender: ${patient.gender}", 40f, 170f, paint)
            canvas.drawText("Phone: ${patient.phone}", 40f, 190f, paint)
        }

        // Draw Analysis Results
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        canvas.drawText("AI SHADE ANALYSIS", 40f, 230f, paint)
        
        paint.color = 0xFF6366F1.toInt()
        paint.textSize = 48f
        canvas.drawText(scanResult.predictedShade, 40f, 290f, paint)
        
        paint.color = 0xFF1E293B.toInt()
        paint.textSize = 16f
        canvas.drawText("Confidence: ${scanResult.confidence}", 40f, 315f, paint)

        // Draw Tooth Image
        try {
            val uri = Uri.parse(scanResult.imageUri)
            val inputStream = context.contentResolver.openInputStream(uri)
            val bitmap = BitmapFactory.decodeStream(inputStream)
            if (bitmap != null) {
                // Resize bitmap to fit in PDF
                val scaledBitmap = scaleBitmap(bitmap, 250, 300)
                canvas.drawBitmap(scaledBitmap, 300f, 200f, null)
            }
            inputStream?.close()
        } catch (e: Exception) {
            e.printStackTrace()
        }

        // Draw Clinical Observations
        paint.color = 0xFF64748B.toInt()
        paint.textSize = 12f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.ITALIC)
        val observation = "The analysis indicates a primary match with VITA shade ${scanResult.predictedShade}."
        canvas.drawText(observation, 40f, 350f, paint)

        // Footer
        paint.color = 0xFFE2E8F0.toInt()
        canvas.drawRect(40f, 780f, 555f, 781f, paint)
        paint.color = 0xFF64748B.toInt()
        paint.textSize = 10f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
        canvas.drawText("Generated by ShadeScan AI Clinical Portal", 40f, 800f, paint)

        pdfDocument.finishPage(page)

        // Save PDF to external files directory
        val fileName = "ShadeScan_Report_${System.currentTimeMillis()}.pdf"
        val filePath = File(context.getExternalFilesDir(null), "reports")
        if (!filePath.exists()) filePath.mkdirs()
        
        val file = File(filePath, fileName)
        return try {
            pdfDocument.writeTo(FileOutputStream(file))
            pdfDocument.close()
            file
        } catch (e: Exception) {
            e.printStackTrace()
            pdfDocument.close()
            null
        }
    }

    private fun scaleBitmap(bitmap: Bitmap, maxWidth: Int, maxHeight: Int): Bitmap {
        val ratio = Math.min(maxWidth.toFloat() / bitmap.width, maxHeight.toFloat() / bitmap.height)
        val width = (bitmap.width * ratio).toInt()
        val height = (bitmap.height * ratio).toInt()
        return Bitmap.createScaledBitmap(bitmap, width, height, true)
    }
}
